set(ANDROID_NDK_HOME $ENV{ANDROID_NDK_HOME})

set(ANDROID_NATIVE_API_LEVEL $ENV{ANDROID_NATIVE_API_LEVEL})
set(ANDROID_TOOLCHAIN $ENV{ANDROID_TOOLCHAIN})
set(ANDROID_ABI $ENV{ANDROID_ABI})
set(ANDROID_STL $ENV{ANDROID_STL})

set(CMAKE_FIND_ROOT_PATH $ENV{CMAKE_FIND_ROOT_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM $ENV{CMAKE_FIND_ROOT_PATH_MODE_PROGRAM})
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY $ENV{CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE $ENV{CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE $ENV{CMAKE_FIND_ROOT_PATH_MODE_PACKAGE})

include(${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake)
